<?php
/**
 * Copyright © 2011-2018 Karliuka Vitalii(karliuka.vitalii@gmail.com)
 *
 * See COPYING.txt for license details.
 */
?>
<?php if ($block->isEnabled()): ?>
<div id="contact-map" class="google-map" data-marker="<?= $block->escapeHtml($block->getMarkerPosition()) ?>"></div>
<script type="text/javascript">
    require(
        ['jquery','Faonni_ContactMap/js/map'],
        function($, map){
            map.init({
                zoom: <?= $block->escapeHtml($block->getZoom()) ?>,
                key: '<?= $block->escapeHtml($block->getApiKey()) ?>',
                locale: '<?= $block->escapeHtml($block->getLocale()) ?>'
            });
        });
</script>
<?php endif ?>
